name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: # optional
        BRANCH: master 
        FOLDER: _site/ 
